version: "3.9"

services:
  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: devops-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://appuser:apppass@postgres:5432/appdb?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - app_network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops-frontend
    ports:
      - "8081:80" # Exposes the frontend app on port 8081
    depends_on:
      - backend
    networks:
      - app_network

  # PostgreSQL Database Service
  postgres:
    image: postgres:16
    container_name: devops-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
